### ISSUE TITLE
Potential Employers:  This person is likely to steal your intellectual property.

### ISSUE THREAD

**Issue by john9631** [OMGUPTA21/MITx-6.00.1x-Introduction-to-Computer-Science-and-Programming-Using-Python#1]
This person committed to edX's honor code which includes not publishing their proprietary material or publishing the answers.

As long as it is up they are stealing from edX and MIT.

Hire at your risk.

**Comment by OMGUPTA21** [comment]
what is the problem it is only help the learner for proper understanding

**Comment by john9631** [comment]
Publishing edX's questions or worse still, answers to those questions is sharing their proprietary information with the world, and when you signed up with edX you made a commitment not to do that - think of yourself as Bradley Manning or Julian Assange.

Would you please remove this from public access - private for your use or that of a potential employer is fine.

**Comment by OMGUPTA21** [comment]
ok
